spring:
  application:
    name: ecoms
  datasource:
    url: jdbc:postgresql://ep-late-sea-aa5s1qni-pooler.westus3.azure.neon.tech:5432/spingapi
    username: spingapi_owner
    password: npg_LGbgT5dRNsF6
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:anime.fans.yt03@gmail.com}
    password: ${MAIL_PASSWORD:qmig unvj zirc nhyy}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

logging:
  level:
    root: INFO
    com.black.ecoms: DEBUG

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000
  mail:
    from: ${MAIL_FROM:anime.fans.yt03@gmail.com}
    subject-code: Your E-Commerce Password Reset Code

